apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myweb
spec:
  selector:
    matchLabels:
      name: my-webapp
  template:
    metadata:
      labels:
        name: my-webapp
    spec:
      containers:
        - name: myweb
          image: naveenkumar003/my-webapp:v1
  replicas: 1
